import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  dashboardTifco: [
    {
      type: 'autogenerated',
      dirName: 'dashboard-tifco',
    },
  ],
  ggob: [
    {
      type: 'autogenerated',
      dirName: 'ggob',
    },
  ],
  notionclone: [
    {
      type: 'autogenerated',
      dirName: 'notion-clone',
    },
  ],
  whatecom: [
    {
      type: 'link',
      label: '🔙 Projects',
      href: '/projects'
    },
    {
      type: 'doc',
      id: 'whatecom/index',
      label: 'Introduction',
    },
    {
      type: 'autogenerated',
      dirName: 'whatecom/docs',
    },
  ],
  qli: [
    {
      type: 'autogenerated',
      dirName: 'qli',
    }
  ],
  cyoa: [
    {
      type: 'autogenerated',
      dirName: 'cyoa',
    }
  ],
  urlshortener: [
    {
      type: 'autogenerated',
      dirName: 'urlshortener',
    }
  ],
};

export default sidebars;
