import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'tutorial-basics'
  //   }
  // ],
  // tutorialExtras: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'tutorial-extras'
  //   }
  // ],
  // docs: [
  //   {
  //     type: 'category',
  //     label: 'Guides',
  //     link: {
  //       type: 'generated-index',
  //       title: 'Project Guides',
  //       description: 'Learn about my projects.',
  //       slug: '/docs/allProjects',
  //       keywords: ['guides'],
  //       image: '/img/docusaurus.png',
  //     },
  //     items: ['cliquiz/index', 'cyoa/index', 'dashboard-tifco/index', 'notion-clone/index', 'urlshortener/index', 'whatecom/index', 'ggob/index'],
  //   },
  // ],
  dashboardTifco: [
    {
      type: 'autogenerated',
      dirName: 'dashboard-tifco',
    },
  ],
  ggob: [
    {
      type: 'autogenerated',
      dirName: 'ggob',
    },
  ],
  notionclone: [
    {
      type: 'autogenerated',
      dirName: 'notion-clone',
    },
  ],
  whatecom: [
    {
      type: 'link',
      label: '🔙 Projects',
      href: '/projects'
    },
    {
      type: 'doc',
      id: 'whatecom/index',
      label: 'Introduction',
    },
    {
      type: 'autogenerated',
      dirName: 'whatecom/docs',
    },
  ],
  cliquiz: [
    {
      type: 'autogenerated',
      dirName: 'cliquiz',
    }
  ],
  cyoa: [
    {
      type: 'autogenerated',
      dirName: 'cyoa',
    }
  ],
  urlshortener: [
    {
      type: 'autogenerated',
      dirName: 'urlshortener',
    }
  ]


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
